version: "3.4"

services:
  image: mongo
  restart: always
  ports:
    - "9115:27017"
  environment:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: password
    MONGO_INITDB_DATABASE: wisdom
  volumes:
    - type: volume
      source: mongo-data
      target: /data/db
volumes:
  mongo-data:
